#
# Travis Setup
#

#
# Test Matrix
#

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TRAVIS_SECOND_USER=travis_two


services:
  - memcached
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
  code_climate:
    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b

matrix:
  fast_finish: true
  include:
    - php: 7.4

before_install:
  # Always remove xdebug.
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
install:
  # install composer dependencies
  - travis_retry composer self-update
  # Fast composer install
  - travis_retry composer global require hirak/prestissimo
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - psql --version
  - mysql --version
  # Config Mysql
  - mysql_upgrade
  - mysql -e 'CREATE DATABASE yiitest;'

script:
  # PHP tests
  - phpdbg -qrr vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --exclude-group wincache,xcache

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  slack:
    -
      rooms:
        -
          secure: dHnLb/RuGpou1pZ6xu8BvQH3r96e8/QlrBVPDfdVcgxX2f41niU99RTBRUJWHr7lz74lqHMm4VAyXTqNLvQDHtDazsvsOJXnbentoun1cqAbH+kgu1xbzxMXYRYdj0uF+85qn08T0DNfb1Avin58fT9D+gpc9VagYoDojg1Gzf9hiEwPp1J5LxF843dhz2hVOGzr3QGADsG1d6jPZHGNiCFz9RM91sAuvWPROc5DYieRJOmE8GRJ0O8wUH4KLiGLyxCsdDjOGZc+3lttCEvNXTAb/s1Mq6DQwrh6ZtEwFhcG7zbQ1mmlS0YTNK3mof/q8Pr2SLwcCBVQBonzo3eCmXp16eT/TxFNmXr86NvXG1sQOsDflSvRLJbtVdlSi4yprGvn4LLm4ug8ZxKKAkQ+1VGX++2gbwKdk7pNs0KRlalCXjCYuNMKgDH63WpyqvMMpkq1nlipdfXKuPOcZKL5WvEVDoK5/py4z0AZeSJA6Z2K+QYOhssUESRQTv7PUJ+rISs8uc2JhEblwBAPUtmiCkH9zrU8vbQNImXgzrlwSmEDHePm8Fa5EtNUfonGnuGUYu2GDc1OqWUBhol2HBFayrh0kiXhshWti4HjWcZFgWZqkuBKRoCeaXNRma4S+ItjE5SEKNtp9rl4OzB8RWyCsECTkDQyrOnKhhn3ctwg3O0=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: TUUaHiKdgiNIOIH2PVfbgMZcC8JS9lqaSsshcBlsHWa2M2S8CkKHw/M2zzqmZ2FNKbRYrLaPDF27JlVKQfrTo4Y/aURhsPK3dhNiajjiNs78O4RMOGW2fdc1s8rQ/Y8dOYEQrAVCQvE1qeiAiiAV3GPFrEQIUfiCbfhy11wjEGRgYPXoRqB2W7LtqH/fPo8UNnBuHh9w/A6cmUyg/LcnyxiYFjqE9+WuhxZgJZc+hA+ZUw7xvu/XjovYbrKrMsFXj+lepvktGXgfmGpdhSteb4aUKfsHvo1iP5dWs95Uo556kEH1E8qEUE+bK2lLENFLh+66303+3WXPoLllkLF7nmHNduPR9ECykI1KghdwZJor7BeVjOJcFQ49ObbxmYUwd5SOxbOwyXTPqAAG3fARo2bisywO4gh3crCymePVHGPflPuidlLlERvKof4Wffz0rN180pwuwdVdMZTsLmjI9/jrClxVelt05p9jmIQTCrgJpwgQNfZIWOj5ammeOyNBu/Fwu1a6sjvWYezYQkbUCyFX50tn3+G4MA1RBtkDMsNy839v6zGP6Ojv2msEJX2bmHFL9MLD1stP6+50Mc5xMINsG9ggjCQsGh303ht+jkLkuwkckYYATsNN8jYTDkFSW1+Z546U5Kq5sRlGVfyz9mT85GFUhrrLpimkUU03oQg=
      on_success: never
      on_failure: always
      on_pull_requests: false
