#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required
group: edge

# build only on master branches
# commented as this prevents people from running builds on their forks:
# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
#branches:
#  only:
#    - master
#    - 3.0


#
# Test Matrix
#

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0
    - TRAVIS_SECOND_USER=travis_two


services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# try running against postgres 9.6
addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
  code_climate:
    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: TASK_TESTS_COVERAGE=1
    - php: nightly
      services:
        - mysql

  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
      mysql --version
    fi

  # initialize databases
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      mysql_upgrade
      travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
      mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
    fi

  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi

  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
  - |
    if [[ $TRAVIS_PHP_VERSION == 7.2 || $TRAVIS_PHP_VERSION = nightly ]]; then
      echo 'Disabled DEPRECATED notifications for PHP >= 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi


script:
  # PHP tests
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group wincache,xcache
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: WhB4A03nwqZjx0qy1sn2TfjJZA5/wUYw/L7L09DiLasuF6MqpzosQK8k/Yief9zatluT1ln5m0xCYGRAeOpVCTXtfeGrxVovc2YwwOo/BNRN5xbBtlrw/WJ7G0tHrFjT8mG+mM2Aq+ASumj79jWGlz0dveP5EBnSwNaku/Sq7NkvoG3kUI7iWY3K1u1whUp/VH5bHjcb5r5IewMyVs9vhcv+lAyIlqdfcu67KQ63XGsDvhOXpg5rSGPUJX+lJ/77r33VLJA7do64cB8P/7W+EarOYV7n5bya7M8cNysIlEqKZ02l+e25wk8sQRQQLisxMm+dcwMdHc97EalFGEJCC92QuCXtVQtH6IK/ez23KixPbmCVoL/DdAwUgjyWjs07pxZ4RUcGUdXfOsjPPnFGXruAKShjdJtkwyjfb6khJ5D+ZX+kDRI+NZga1YTk5oV88H5KZYOHVvC4S1GYYgygkT3/+1PlmAeM0YIKA+ubZuSHnmQ5FKos1S5mWCc6AOlh6zjsMlXqvASB0RlvLSTbfjuaDB3mRRzKhCNIRQyhXD5ge/UIoGe0wmTAM6GB9aXmPglDIX8isbD5vhMWAdsU/w6bg7HQ9JQdHGfT4TtAG+l2o+NeBieSq/fCxRvz/CesElBQza1gPlqdJy/yJ1RTwkVExEOh039SYDVNAAH75Ys=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: ZCdyydlQ7RyM29/q+alospaQQ/QL/9KW5+YKlYKtrMH5u2lx1vxMUE+QUug1e1W01HVcox4qLISIugYPWqpcdEcBzSgYWMY9SGeh9Zr4RSp+t+i09h6OtsE9h0va9tcJFZK9ULt9T7BKjcV3wDEsXqVs/94XMepjQk8pDi9DIWpIO9v+9xmo8MZRrwhQ0bFlamNjN+KGJfkMWTSQRPa10gvYOGcICrtw0nvZPdDddedTA0HKzEkwYswirJz+98HVDjRIFLFdvQQUVwBgwxBuEh3UCNiEQJPNRS4pU3XCBD6l89fVPhpJP0X7LhRRKEK6TROBM4JlfmPBryXgrzxLoT0Toerald+Q5y0vTKmNTMkRAIS6OvShXymenEy5T2dQImQWEBFD0p6/t+VbjVtbs/m+Pn3unfeFqx6Pa4jf994fpxWipNycGr4Woya3a+8LG7LBz5mw13P/0El8BIq02UjnUEiT/bq903VA7VKUWS3if8ffulCtcVWEr+nZTkWbcrf2oza6n/t+NKttUCJxoJ9QbutBejqC6dv9iJEp5C3nDBsBNO+KSF+T/PfhuzpCLzdzRPoxa7YbUGvi8kS0MAOYzxG/moMj9pVrzqAS1FIx6n8i0xVz/e0SJWd1UH2ajFkun/8/beMh03Fp0mQijWB3tH0KmN02ufKxOK5/3mM=
      on_success: never
      on_failure: always
      on_pull_requests: false
